"""empty message

Revision ID: d66eebf1d05d
Revises: 26fd360d37b3
Create Date: 2020-07-29 23:12:52.677367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66eebf1d05d'
down_revision = '26fd360d37b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todos SET completed=False WHERE completed IS NULL;')

    op.alter_column('todos', 'completed', nullable = False)
   # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
